version: '3'

services:
  couchdb:
    build:
      context: .
      dockerfile: ./couchdb/Dockerfile
    tty: true
    ports:
      - 5984:5984
    volumes:
      - data:/opt/couchdb/data

  blockchain:
    build:
      context: .
      dockerfile: ./blockchain/Dockerfile
      
      args: 
        - ACCESS_TOKEN=enter_github_access_token
        - GITHUB_USERNAME=enter_github_username
    tty: true
    ports:
      - 26656:26656
      - 26657:26657
      - 26660:26660
      - 6060:6060
      - 9090:9090
      - 1317:1317
    volumes:
      - chain:/root/.bitbadgeschain
      - chain:/root/.bitbadges

  express:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args: 
        - ENV_FILE=.env
    tty: true
    ports:
      - 3001:3001
    depends_on:
      - blockchain
      - couchdb

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   environment:
  #     - BITBADGES_IO=true
  #   tty: true
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - blockchain
  #     - couchdb

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    tty: true
    ports:
      - 80:80
      - 443:443
    depends_on:
      - express

volumes:
  data:
  chain:
