version: '3'

services:
  blockchain:
    build:
      context: .
      dockerfile: ./blockchain/Dockerfile
    tty: true
    command: run start --api.enable --api.enabled-unsafe-cors --pruning nothing
    ports:
      - 26656:26656
      - 26657:26657
      - 26660:26660
      - 6060:6060
      - 9090:9090
      - 1317:1317
    # volumes:
    #   - blockchain-config/config:/root/.bitbadgeschain/config
    #   - blockchain-config/data:/root/.bitbadgeschain/data


  express:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args: 
        - ENV_FILE=.env
    command: setup-and-run 
    tty: true
    ports:
      - 3001:3001

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    tty: true
    ports:
      - 80:80
      - 443:443
    depends_on:
      - express
      - blockchain

volumes:
  data:
  chain:
